// <auto-generated />
using LandenModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LandenModel.Migrations
{
    [DbContext(typeof(LandenContext))]
    [Migration("20260817110659_UpdateSeedData")]
    partial class UpdateSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LandenModel.Land", b =>
                {
                    b.Property<string>("LandCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LandCode");

                    b.ToTable("Landen");

                    b.HasData(
                        new
                        {
                            LandCode = "BEL",
                            Naam = "België"
                        },
                        new
                        {
                            LandCode = "DEU",
                            Naam = "Duitsland"
                        },
                        new
                        {
                            LandCode = "FRA",
                            Naam = "Frankrijk"
                        },
                        new
                        {
                            LandCode = "LUX",
                            Naam = "Luxemburg"
                        },
                        new
                        {
                            LandCode = "NLD",
                            Naam = "Nederland"
                        });
                });

            modelBuilder.Entity("LandenModel.LandenTaal", b =>
                {
                    b.Property<string>("LandCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TaalCode")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LandCode", "TaalCode");

                    b.HasIndex("TaalCode");

                    b.ToTable("LandenTalen");

                    b.HasData(
                        new
                        {
                            LandCode = "BEL",
                            TaalCode = "de"
                        },
                        new
                        {
                            LandCode = "BEL",
                            TaalCode = "fr"
                        },
                        new
                        {
                            LandCode = "BEL",
                            TaalCode = "nl"
                        },
                        new
                        {
                            LandCode = "DEU",
                            TaalCode = "de"
                        },
                        new
                        {
                            LandCode = "FRA",
                            TaalCode = "fr"
                        },
                        new
                        {
                            LandCode = "LUX",
                            TaalCode = "de"
                        },
                        new
                        {
                            LandCode = "LUX",
                            TaalCode = "fr"
                        },
                        new
                        {
                            LandCode = "LUX",
                            TaalCode = "lb"
                        },
                        new
                        {
                            LandCode = "NLD",
                            TaalCode = "nl"
                        });
                });

            modelBuilder.Entity("LandenModel.Stad", b =>
                {
                    b.Property<int>("StadNr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StadNr"));

                    b.Property<string>("LandCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StadNr");

                    b.HasIndex("LandCode");

                    b.ToTable("Steden");

                    b.HasData(
                        new
                        {
                            StadNr = 1,
                            LandCode = "BEL",
                            Naam = "Brussel"
                        },
                        new
                        {
                            StadNr = 2,
                            LandCode = "BEL",
                            Naam = "Antwerpen"
                        },
                        new
                        {
                            StadNr = 3,
                            LandCode = "BEL",
                            Naam = "Luik"
                        },
                        new
                        {
                            StadNr = 4,
                            LandCode = "NLD",
                            Naam = "Amsterdam"
                        },
                        new
                        {
                            StadNr = 5,
                            LandCode = "NLD",
                            Naam = "Den Haag"
                        },
                        new
                        {
                            StadNr = 6,
                            LandCode = "NLD",
                            Naam = "Rotterdam"
                        },
                        new
                        {
                            StadNr = 7,
                            LandCode = "DEU",
                            Naam = "Berlijn"
                        },
                        new
                        {
                            StadNr = 8,
                            LandCode = "DEU",
                            Naam = "Hamburg"
                        },
                        new
                        {
                            StadNr = 9,
                            LandCode = "DEU",
                            Naam = "München"
                        },
                        new
                        {
                            StadNr = 10,
                            LandCode = "LUX",
                            Naam = "Luxemburg"
                        },
                        new
                        {
                            StadNr = 11,
                            LandCode = "FRA",
                            Naam = "Parijs"
                        },
                        new
                        {
                            StadNr = 12,
                            LandCode = "FRA",
                            Naam = "Marseille"
                        },
                        new
                        {
                            StadNr = 13,
                            LandCode = "FRA",
                            Naam = "Lyon"
                        });
                });

            modelBuilder.Entity("LandenModel.Taal", b =>
                {
                    b.Property<string>("TaalCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TaalCode");

                    b.ToTable("Talen");

                    b.HasData(
                        new
                        {
                            TaalCode = "de",
                            Naam = "Duits"
                        },
                        new
                        {
                            TaalCode = "fr",
                            Naam = "Frans"
                        },
                        new
                        {
                            TaalCode = "lb",
                            Naam = "Luxemburgs"
                        },
                        new
                        {
                            TaalCode = "nl",
                            Naam = "Nederlands"
                        });
                });

            modelBuilder.Entity("LandenModel.LandenTaal", b =>
                {
                    b.HasOne("LandenModel.Land", "Land")
                        .WithMany("LandenTalen")
                        .HasForeignKey("LandCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LandenModel.Taal", "Taal")
                        .WithMany("LandenTalen")
                        .HasForeignKey("TaalCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Land");

                    b.Navigation("Taal");
                });

            modelBuilder.Entity("LandenModel.Stad", b =>
                {
                    b.HasOne("LandenModel.Land", "Land")
                        .WithMany("Steden")
                        .HasForeignKey("LandCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Land");
                });

            modelBuilder.Entity("LandenModel.Land", b =>
                {
                    b.Navigation("LandenTalen");

                    b.Navigation("Steden");
                });

            modelBuilder.Entity("LandenModel.Taal", b =>
                {
                    b.Navigation("LandenTalen");
                });
#pragma warning restore 612, 618
        }
    }
}
