// <auto-generated />
using LandenModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LandenModel.Migrations
{
    [DbContext(typeof(LandenContext))]
    [Migration("20260817081459_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LandenModel.Land", b =>
                {
                    b.Property<string>("LandCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LandCode");

                    b.ToTable("Landen");
                });

            modelBuilder.Entity("LandenModel.LandenTaal", b =>
                {
                    b.Property<string>("LandCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TaalCode")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LandCode", "TaalCode");

                    b.HasIndex("TaalCode");

                    b.ToTable("LandenTalen");
                });

            modelBuilder.Entity("LandenModel.Stad", b =>
                {
                    b.Property<int>("StadNr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StadNr"));

                    b.Property<string>("LandCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StadNr");

                    b.HasIndex("LandCode");

                    b.ToTable("Steden");
                });

            modelBuilder.Entity("LandenModel.Taal", b =>
                {
                    b.Property<string>("TaalCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TaalCode");

                    b.ToTable("Talen");
                });

            modelBuilder.Entity("LandenModel.LandenTaal", b =>
                {
                    b.HasOne("LandenModel.Land", "Land")
                        .WithMany("LandenTalen")
                        .HasForeignKey("LandCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LandenModel.Taal", "Taal")
                        .WithMany("LandenTalen")
                        .HasForeignKey("TaalCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Land");

                    b.Navigation("Taal");
                });

            modelBuilder.Entity("LandenModel.Stad", b =>
                {
                    b.HasOne("LandenModel.Land", "Land")
                        .WithMany("Steden")
                        .HasForeignKey("LandCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Land");
                });

            modelBuilder.Entity("LandenModel.Land", b =>
                {
                    b.Navigation("LandenTalen");

                    b.Navigation("Steden");
                });

            modelBuilder.Entity("LandenModel.Taal", b =>
                {
                    b.Navigation("LandenTalen");
                });
#pragma warning restore 612, 618
        }
    }
}
